# Generated by Django 4.0.5 on 2022-06-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('study_name', models.CharField(max_length=256)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyImages',
            fields=[
                ('study_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=256)),
                ('photo_type', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='images')),
                ('study_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.study')),
            ],
        ),
    ]
